---
name: Comment on PR2

on:
  # workflow_dispatch:
  #   inputs:
  #     pr_number:
  #       description: 'Pull Request number'
  #       required: true
  #     text:
  #       description: 'Comment text'
  #       required: false
  #       default: 'test text'

  repository_dispatch:
    types: [comment]
jobs:
  comment:
    runs-on: ubuntu-latest
    name: Comment
    steps:
      - name: Comment given text
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: '${{ github.event.client_payload.pr_number }}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'DEF'
            })
