name: Run Command

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo '1' > ./pr/NR

      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/